### ISSUE TITLE
Kodi "Matrix" update

### ISSUE THREAD

**Issue by emberderek** [rimago/rpi-kodi#10]
Hi,

Any plane in the near future for update to Matrix?

Thx & regrads

**Comment by rimago** [comment]
Yes, I just need to upgrade my Raspbian to bullseye first.
I hope to be able to do that in the next weeks.

**Comment by rimago** [comment]
Finally it is done.
The latest tag refers now to kodi 19.4 (matrix).

I did not do too much testing, so let me know if you find any problems.
